"""Пересобирает описания листинга: catch-блок, топ-фичи, затем прежний текст."""
import pathlib

OUT = pathlib.Path("/Users/nickeo23/code_projects/Chrome_youtube_player/store/descriptions")

# catch — 2 строки-крючка; head — заголовок списка; bullets — 8 коротких пунктов
BLOCKS = {
"en": ("Watch YouTube while you actually work. One click and the video floats\nabove every window — with the controls YouTube never gave you.",
 "WHY PEOPLE KEEP IT",
 ["Truly always on top — never falls behind your editor",
  "Nothing restarts: the real YouTube player moves into the window",
  "Speed 0.25–3x and volume up to 300%",
  "A-B loop for practice, plus loop the whole video",
  "Sleep timer that really pauses, up to 12 hours",
  "Sponsor segments marked in green and skipped in one click",
  "Shorts in a vertical window that advances by itself",
  "Video only — no cards, no shopping overlays, no clutter"]),
"ru": ("Смотрите YouTube и правда работайте. Один клик — и видео висит поверх\nвсех окон с теми кнопками, которых у YouTube никогда не было.",
 "ЗА ЧТО ЕГО ОСТАВЛЯЮТ",
 ["По-настоящему поверх всех окон — не проваливается за редактор",
  "Ничего не перезапускается: в окно переезжает сам плеер YouTube",
  "Скорость 0.25–3x и громкость до 300%",
  "A-B повтор для отработки плюс зацикливание всего видео",
  "Таймер сна, который действительно ставит паузу, до 12 часов",
  "Спонсорские вставки подсвечены и пропускаются одним кликом",
  "Шортсы в вертикальном окне с автопереходом",
  "Только видео — без карточек, товаров и лишнего интерфейса"]),
"es": ("Mira YouTube y trabaja de verdad. Un clic y el vídeo flota sobre todas las\nventanas, con los controles que YouTube nunca te dio.",
 "POR QUÉ LA GENTE LO CONSERVA",
 ["Siempre visible de verdad: nunca queda detrás de tu editor",
  "Nada se reinicia: el propio reproductor de YouTube pasa a la ventana",
  "Velocidad 0,25–3x y volumen hasta el 300 %",
  "Bucle A-B para practicar y repetición del vídeo entero",
  "Temporizador que pausa de verdad, hasta 12 horas",
  "Patrocinios marcados en verde y saltados con un clic",
  "Shorts en ventana vertical que avanza sola",
  "Solo vídeo: sin tarjetas, sin anuncios de tienda, sin ruido"]),
"pt_BR": ("Assista ao YouTube e trabalhe de verdade. Um clique e o vídeo flutua sobre\ntodas as janelas, com os controles que o YouTube nunca te deu.",
 "POR QUE AS PESSOAS MANTÊM",
 ["Sempre à frente de verdade: nunca some atrás do seu editor",
  "Nada recomeça: o próprio player do YouTube vai para a janela",
  "Velocidade 0,25–3x e volume até 300%",
  "Repetição A-B para treinar e loop do vídeo inteiro",
  "Timer que pausa de verdade, até 12 horas",
  "Patrocínios marcados em verde e pulados com um clique",
  "Shorts em janela vertical que avança sozinha",
  "Só vídeo: sem cards, sem vitrine, sem bagunça"]),
"de": ("YouTube schauen und wirklich arbeiten. Ein Klick und das Video schwebt über\nallen Fenstern — mit den Bedienelementen, die YouTube nie geliefert hat.",
 "WARUM ES INSTALLIERT BLEIBT",
 ["Wirklich immer im Vordergrund — rutscht nie hinter den Editor",
  "Nichts startet neu: der echte YouTube-Player zieht ins Fenster um",
  "Tempo 0,25–3x und Lautstärke bis 300 %",
  "A-B-Schleife zum Üben, dazu das ganze Video wiederholen",
  "Sleeptimer, der wirklich pausiert, bis zu 12 Stunden",
  "Sponsor-Abschnitte grün markiert und mit einem Klick übersprungen",
  "Shorts im Hochkantfenster, das von selbst weiterspringt",
  "Nur Video — keine Karten, keine Shopping-Banner, kein Ballast"]),
"ja": ("仕事をしながらYouTubeを。ワンクリックで動画がすべてのウィンドウの上に浮かび、\nYouTubeにはなかった操作がそろいます。",
 "使い続けられる理由",
 ["本当に最前面 — 作業中のウィンドウの後ろに回りません",
  "再生し直しなし：YouTubeのプレーヤーごと移動します",
  "速度0.25〜3倍、音量は最大300%",
  "練習向けのA-Bリピートと動画全体のループ",
  "本当に一時停止するスリープタイマー（最長12時間）",
  "スポンサー部分は緑で表示、ワンクリックでスキップ",
  "ショートは縦型ウィンドウで自動的に次へ",
  "動画だけ — カードも商品棚も雑音もなし"]),
"fr": ("Regardez YouTube et travaillez vraiment. Un clic et la vidéo flotte au-dessus\nde toutes les fenêtres, avec les commandes que YouTube n'a jamais données.",
 "POURQUOI ON LE GARDE",
 ["Vraiment au premier plan : ne passe jamais derrière votre éditeur",
  "Rien ne redémarre : le vrai lecteur YouTube passe dans la fenêtre",
  "Vitesse 0,25–3x et volume jusqu'à 300 %",
  "Boucle A-B pour s'entraîner, et répétition de toute la vidéo",
  "Minuterie qui met vraiment en pause, jusqu'à 12 heures",
  "Passages sponsorisés marqués en vert et évités en un clic",
  "Shorts en fenêtre verticale qui enchaîne toute seule",
  "Rien que la vidéo : ni cartes, ni boutique, ni fouillis"]),
"id": ("Menonton YouTube sambil benar-benar bekerja. Satu klik dan video mengambang\ndi atas semua jendela, dengan kendali yang tak pernah diberikan YouTube.",
 "ALASAN ORANG TETAP MEMAKAINYA",
 ["Benar-benar selalu di atas — tak pernah tenggelam di belakang editor",
  "Tidak ada yang diulang: pemutar YouTube asli pindah ke jendela",
  "Kecepatan 0,25–3x dan volume sampai 300%",
  "Pengulangan A-B untuk berlatih, plus loop seluruh video",
  "Pengatur waktu tidur yang benar-benar menjeda, sampai 12 jam",
  "Segmen sponsor ditandai hijau dan dilewati satu klik",
  "Shorts di jendela vertikal yang lanjut sendiri",
  "Hanya video — tanpa kartu, tanpa etalase, tanpa gangguan"]),
"tr": ("YouTube izleyin ama gerçekten çalışın. Tek tıkla video tüm pencerelerin\nüstünde durur — YouTube'un hiç vermediği kontrollerle.",
 "NEDEN SİLİNMİYOR",
 ["Gerçekten her zaman üstte — editörünüzün arkasına düşmez",
  "Hiçbir şey baştan başlamaz: YouTube oynatıcısının kendisi taşınır",
  "0,25–3x hız ve %300'e kadar ses",
  "Çalışmak için A-B döngüsü, ayrıca videonun tamamını döngüye alma",
  "Gerçekten duraklatan uyku zamanlayıcısı, 12 saate kadar",
  "Sponsor bölümleri yeşil işaretlenir, tek tıkla atlanır",
  "Shorts dikey pencerede kendiliğinden ilerler",
  "Yalnızca video — kart yok, vitrin yok, karmaşa yok"]),
"hi": ("काम करते हुए YouTube देखिए। एक क्लिक और वीडियो हर विंडो के ऊपर तैरता है —\nउन कंट्रोल के साथ जो YouTube ने कभी नहीं दिए।",
 "लोग इसे क्यों रखते हैं",
 ["सचमुच हमेशा सबसे ऊपर — आपके एडिटर के पीछे नहीं जाता",
  "कुछ भी दोबारा शुरू नहीं होता: असली YouTube प्लेयर ही विंडो में जाता है",
  "स्पीड 0.25–3x और वॉल्यूम 300% तक",
  "अभ्यास के लिए A-B लूप, साथ में पूरे वीडियो का लूप",
  "स्लीप टाइमर जो सचमुच रोकता है, 12 घंटे तक",
  "स्पॉन्सर हिस्से हरे रंग में और एक क्लिक में पार",
  "Shorts खड़ी विंडो में, अपने आप अगला",
  "सिर्फ़ वीडियो — न कार्ड, न दुकान, न शोर"]),
"ko": ("일하면서 YouTube를 보세요. 한 번 클릭하면 영상이 모든 창 위에 떠 있고,\nYouTube가 주지 않던 조작이 함께 옵니다.",
 "계속 쓰게 되는 이유",
 ["진짜 항상 위 — 작업 창 뒤로 밀리지 않습니다",
  "다시 시작 없음: YouTube 플레이어 자체가 창으로 옮겨갑니다",
  "속도 0.25~3배속, 음량 최대 300%",
  "연습용 A-B 반복과 영상 전체 반복",
  "실제로 일시정지하는 취침 타이머, 최대 12시간",
  "스폰서 구간은 초록색 표시, 한 번에 건너뛰기",
  "Shorts는 세로 창에서 자동으로 다음 편으로",
  "영상만 — 카드도, 쇼핑도, 잡동사니도 없음"]),
"it": ("Guarda YouTube e lavora davvero. Un clic e il video resta sopra ogni finestra,\ncon i comandi che YouTube non ha mai dato.",
 "PERCHÉ RESTA INSTALLATA",
 ["Davvero sempre in primo piano: non finisce dietro l'editor",
  "Niente riparte: si sposta il lettore YouTube vero e proprio",
  "Velocità 0,25–3x e volume fino al 300%",
  "Loop A-B per esercitarsi e ripetizione dell'intero video",
  "Timer che mette davvero in pausa, fino a 12 ore",
  "Segmenti sponsorizzati in verde, saltati con un clic",
  "Shorts in finestra verticale che va avanti da sola",
  "Solo video: niente schede, niente vetrina, niente rumore"]),
"pl": ("Oglądaj YouTube i naprawdę pracuj. Jedno kliknięcie i wideo unosi się nad\nwszystkimi oknami — z przyciskami, których YouTube nigdy nie dał.",
 "DLACZEGO ZOSTAJE NA STAŁE",
 ["Naprawdę zawsze na wierzchu — nie chowa się za edytorem",
  "Nic się nie restartuje: do okna przenosi się sam odtwarzacz YouTube",
  "Prędkość 0,25–3x i głośność do 300%",
  "Pętla A-B do ćwiczeń oraz zapętlenie całego filmu",
  "Wyłącznik czasowy, który naprawdę wstrzymuje, do 12 godzin",
  "Fragmenty sponsorowane na zielono i pomijane jednym kliknięciem",
  "Shorts w pionowym oknie, które samo przewija dalej",
  "Tylko wideo — bez kart, bez sklepu, bez bałaganu"]),
"uk": ("Дивіться YouTube і справді працюйте. Один клік — і відео тримається поверх\nусіх вікон із кнопками, яких YouTube ніколи не давав.",
 "ЧОМУ ЙОГО ЗАЛИШАЮТЬ",
 ["По-справжньому поверх усіх вікон — не провалюється за редактор",
  "Ніщо не перезапускається: у вікно переїжджає сам плеєр YouTube",
  "Швидкість 0,25–3x і гучність до 300%",
  "A-B повтор для відпрацювання плюс зациклення всього відео",
  "Таймер сну, який справді ставить на паузу, до 12 годин",
  "Спонсорські вставки підсвічені й пропускаються одним кліком",
  "Shorts у вертикальному вікні з автопереходом",
  "Лише відео — без карток, вітрин і зайвого інтерфейсу"]),
}

for lang, (catch, head, bullets) in BLOCKS.items():
    path = OUT / f"{lang}.txt"
    body = path.read_text().strip()
    if body.startswith(catch.split("\n")[0][:30]):
        print(f"{lang}: уже перестроен"); continue
    block = catch + "\n\n\n" + head + "\n\n" + "\n".join(f"• {b}" for b in bullets) + "\n\n\n"
    path.write_text(block + body + "\n")
    print(f"{lang}: {len(block + body)} символов")

# краткие версии больше не нужны — в консоли краткого поля нет,
# сводку берут из description в манифесте
removed = 0
for short in OUT.glob("*-short.txt"):
    short.unlink(); removed += 1
print("удалено кратких файлов:", removed)
